### PR TITLE
docs update & bump to 0.12

### PR DESCRIPTION
**Pull request by kylebarron**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
- [x] I ran cargo fmt
---

- Update top-level crate documentation with new information about geo-traits
- Add simple docstrings to all public functions
- Remove panic

### CODE REVIEW

**Comment by michaelkirk** [comment]
Should we make the switch to std::fmt::Write before releasing?

**Comment by kylebarron** [comment]
> Should we make the switch to std::fmt::Write before releasing?

We already have `std::fmt::Write`. I was thinking more whether we should switch to `std::io::Write`. But it sounds like no.

**Comment by kylebarron** [comment]
> The main sticking point for me: It seems like while I can stream WKT to a File (and friends) with io::Write, I can't do that with fmt::Write.

I think you can still stream WKT to `io::Write` with a small adapter: https://github.com/georust/wkt/pull/126/files#diff-afc819097d10bcb89581940115867e201017cd2bc9413c58f01b3dd610170f83R39-R49

Every call to `write_str` gets translated into the underlying `io::Write::write`, right? So I don't think there's any buffering still.

It's mostly a little ugly that you lost the content of any `io::Error` because that gets mapped to a `fmt::Error`.

**Comment by michaelkirk** [comment]
> I think you can still stream WKT to io::Write with a small adapter: https://github.com/georust/wkt/pull/126/files#diff-afc819097d10bcb89581940115867e201017cd2bc9413c58f01b3dd610170f83R39-R49

You're right again!

> It's mostly a little ugly that you lost the content of any io::Error because that gets mapped to a fmt::Error.

I might see a way around this... after I wrap up some georust/geo stuff, I'll take a swing at it.

**Review by michaelkirk — APPROVED** [review]
LGTM 

Anything else you want to include before releasing @kylebarron or anyone else?

Otherwise, I'll merge and release this tomorrow to give anybody else a final chance to weigh in.

**Comment by kylebarron** [comment]
It looks good to me! https://github.com/georust/wkt/issues/125 would be nice to get to in the medium term, but I don't think it should block a release.

**Comment by michaelkirk** [comment]
released: https://crates.io/crates/wkt/0.12.0
tagged: https://github.com/georust/wkt/releases/tag/0.12.0

**Pull request merged**
