### PR TITLE
Easier serialization of wkt with ToWkt::wkt_string/write_wkt

### LINKED ISSUE #55: Better way to serialize to wkt?
I was trying to write a geo-type as WKT to file, and this is what I came up with:

```
    let points = include!("../src/algorithm/test_fixtures/louisiana.rs");
    let geo_linestring: geo::LineString<f32> = points.into();
    use wkt::ToWkt;
    let wkt: wkt::Wkt<_> = geo::Geometry::from(geo_linestring).to_wkt();
    let wkt_linestring = wkt.items.first().unwrap();
    let serialized = format!("{}", wkt_linestring);
    println!("{}", &serialized);
```

Is there already better way?

I was hoping for something like:
```diff
    let points = include!("../src/algorithm/test_fixtures/louisiana.rs");
    let geo_linestring: geo::LineString<f32> = points.into();
    use wkt::ToWkt;
    let wkt: wkt::Wkt<_> = geo::Geometry::from(geo_linestring).to_wkt();
-   let wkt_linestring = wkt.items.first().unwrap();
-   let serialized = format!("{}", wkt_linestring);
+   let serialized = wkt.to_string()
    println!("{}", &serialized);
```

Or like [`serde_jsons::to_writer`](https://docs.serde.rs/serde_json/fn.to_writer.html)
```diff
    let points = include!("../src/algorithm/test_fixtures/louisiana.rs");
    let geo_linestring: geo::LineString<f32> = points.into();
    use wkt::ToWkt;
    let wkt: wkt::Wkt<_> = geo::Geometry::from(geo_linestring).to_wkt();
-   let wkt_linestring = wkt.items.first().unwrap();
-   let serialized = format!("{}", wkt_linestring);
+   let file = File::create("/tmp/foo").unwrap();
+   let mut writer = BufWriter::new(file);
+   wkt::to_writer(&mut writer, wkt);
    println!("{}", &serialized);
```

Any thoughts?

### PR DESCRIPTION
**Pull request by michaelkirk**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
- [x] I ran cargo fmt
---
Fixes #55 - adds an easier API to serialize a geo-type.

~~Depends on #86, so merge that first.~~ Merged!

~~partially conflicts with #88, because I'm relying on the `ToWkt` trait.~~ superseded!

### CODE REVIEW

**Comment by categulario** [comment]
At this point I do think that this impl goes in the right direction, but it is not (for me) the best possible scenario

**Comment by michaelkirk** [comment]
Ok, l'm going to call this ready for review. Please take a look anyone whose interested.

**Review by urschrei — APPROVED** [review]
I like where this has ended up.

**Comment by michaelkirk** [comment]
bors r=urschrei

**Comment by michaelkirk** [comment]
bors r=urschrei

**Pull request merged**
